version: '3.7'

services:
  sonarr:
    image: linuxserver/sonarr:latest
    restart: unless-stopped
    ports:
      - 8989:8989/tcp
    env_file: 
        - .env
        - ../global.env    
    hostname: liofal.synology.me
    volumes:
      - /volume1/docker/sonarr/config:/config
      - /volume1/sonarr:/downloads/complete/sonarr
      - /volume1/tvshows:/tv
    logging:
      driver: json-file
    deploy:
      resources:
        limits:
          memory: 128M
    networks:
      sonarr:
      jackett:
      transmission:
  
networks:
  sonarr:
    name: sonarr
  jackett:
    external: 
      name: jackett
  transmission:
    external: 
      name: transmission
  