version: '3.7'

x-common-variables: &common-variables
  TERM: "xterm"
  TZ: "Europe/Brussels"
  PGID: "100"
  PUID: "1027"

services:
  gekko:
    image: liofal/gekko:latest
    restart: unless-stopped
    ports:
      - 3000:3000/tcp
    environment:
      <<: *common-variables
    hostname: liofal.synology.me
    volumes:
      - history:/usr/src/app/history
      - ./config.js:/usr/src/app/config.js:ro
      - ./config.js:/usr/src/app/web/routes/baseConfig.js:ro
    links:
      - redis
    depends_on: 
      - redis
    logging:
      driver: syslog
    deploy:
      resources:
        limits:
          memory: 128M
    networks:
      gekko:

  redis:
    image: redis:latest
    volumes:
      - data:/data
    networks:
      gekko:

networks:
  gekko:
volumes:
  data:
  history:
