version: '3.7'

x-common: &common
    image: liofal/streamlink:1.4.0-beta
    build:
      context: .
      dockerfile: Dockerfile
    env_file: 
        - ../global.env    
        - default.env
        - clientid.env
    user: 1027:100
    logging:
      driver: json-file
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 256M
    volumes:
    - /volume1/twitch:/download

services:
 test:
    <<: *common
    volumes:
    - ./streamlink-recorder.py:/streamlink-recorder.py
    - /volume1/twitch:/download
    environment:
      - user=polt
      - quality=worst
 
 trap321:
    <<: *common
    environment:
      - user=trap321
 
 eternalenvyy:
    <<: *common
    environment:
      - user=eternalenvyy
 
 seed_sc2:
    <<: *common
    environment:
      - user=seed_sc2
 
 truesc2:
    <<: *common
    environment:
      - user=truesc2
 
 scbomber:
    <<: *common
    environment:
      - user=scbomber
 
 egjd:
    <<: *common
    environment:
      - user=egjd
 
 dongraegu:
    <<: *common
    environment:
      - user=dongraegu
 
 leenock_:
    <<: *common
    environment:
      - user=leenock_
 
 qkrfuddn0:
    <<: *common
    environment:
      - user=qkrfuddn0
 
 jinairsos1:
    <<: *common
    environment:
      - user=jinairsos1
 
 gsl:
    <<: *common
    environment:
      - user=gsl
 
 starcraft:
    <<: *common
    environment:
      - user=starcraft
 
 maru072:
    <<: *common
    environment:
      - user=maru072
 
 roguejinair:
    <<: *common
    environment:
      - user=roguejinair
 
 sc2dear:
    <<: *common
    environment:
      - user=sc2dear
 
 hassc2:
    <<: *common
    environment:
      - user=hassc2
 
 krfantasy:
    <<: *common
    environment:
      - user=krfantasy
 
 sc2solar:
    <<: *common
    environment:
      - user=sc2solar
 
 SC2_Ragnarok:
    <<: *common
    environment:
      - user=SC2_Ragnarok
 
 sc2creator:
    <<: *common
    environment:
      - user=sc2creator

 sc2_zest:
    <<: *common
    environment:
      - user=sc2_zest
 
 sc2soo:
    <<: *common
    environment:
      - user=sc2soo
 
 kimclassic:
    <<: *common
    environment:
      - user=kimclassic
 
 serral:
    <<: *common
    environment:
      - user=serral

 reynor2002:
    <<: *common
    environment:
      - user=reynor2002

 sc2tyty:
    <<: *common
    environment:
      - user=sc2tyty
 
 innovation_s2:
    <<: *common
    environment:
      - user=innovation_s2
  
 gumiho:
    <<: *common
    environment:
      - user=gumiho
  
 gostephano:
    <<: *common
    environment:
      - user=gostephano
 