version: '3.7'

x-common-variables: &common-variables
  TERM: "xterm"
  TZ: "Europe/Brussels"
  PLEX_CLAIM: "claim-6ZPrfseEvhBkspCDbZtG"
  ADVERTISE_IP: "http://liofal.synology.me:32400/"
  CHANGE_CONFIG_DIR_OWNERSHIP: "true"
  PLEX_UID: "1027"

services:
  plex:
    container_name: plex
    image: plexinc/pms-docker
    restart: unless-stopped
    ports:
      - 32400:32400/tcp
      - 3005:3005/tcp
      - 8324:8324/tcp
      - 32469:32469/tcp
      - 1900:1900/udp
      - 32410:32410/udp
      - 32412:32412/udp
      - 32413:32413/udp
      - 32414:32414/udp
    environment:
      <<: *common-variables
    hostname: liofal.synology.me
    volumes:
      - /volume1/docker/plex/config:/config
      - /volume1/docker/plex/transcode:/transcode
      - /volume1/tvshows:/data/tvshows
      - /volume1/movies:/data/movies
    logging:
      driver: syslog
    deploy:
      resources:
        limits:
          memory: 128M