version: '3.7'

services:

  init-guac-db:
      image: guacamole/guacamole:latest
      command: ["/bin/sh", "-c", "test -e /init/initdb.sql && echo 'init file already exists' || /opt/guacamole/bin/initdb.sh --postgres > /init/initdb.sql" ]
      volumes:
        - dbinit:/init    
      env_file: 
        - .env
        - ../global.env
      hostname: init-guac-db
      logging:
        driver: json-file
      deploy:
        resources:
          limits:
            memory: 128M
      networks:
        guacamole:

  postgres:
      image: postgres:latest
      restart: unless-stopped
      volumes:
        - dbinit:/docker-entrypoint-initdb.d        
        - dbdata:/var/lib/postgresql/data
      env_file: 
        - .env
        - ../global.env
      hostname: postgres
      depends_on:
        - init-guac-db
      logging:
        driver: json-file
      deploy:
        resources:
          limits:
            memory: 128M
      networks:
        guacamole:

  guacd:
    image: guacamole/guacd:latest
    restart: unless-stopped
    hostname: guacd
    logging:
      driver: json-file
    networks:
      guacamole:

  guac:
    image: guacamole/guacamole:latest
    restart: unless-stopped
    
    links: 
      - postgres
      - guacd
    depends_on: 
      - postgres
      - guacd
    ports:
      - "8080:8080"
    environment:
      GUACD_HOSTNAME: guacd
      POSTGRES_HOSTNAME: postgres
      POSTGRES_DATABASE: ${POSTGRES_USER:-guacadb} 
      POSTGRES_USER: ${POSTGRES_USER:-guacadb} 
      POSTGRES_PASSWORD:
      LETSENCRYPT_TEST: ${LETSENCRYPT_TEST:-false}
      VIRTUAL_HOST: 
      LETSENCRYPT_HOST: ${VIRTUAL_HOST}
      LETSENCRYPT_EMAIL: 
    logging:
      driver: json-file
    networks:
      guacamole:

  
networks:
  guacamole:
volumes:
  dbinit:
  dbdata:
