version: '3.7'

x-common-variables: &common-variables
  TERM: "xterm"
  TZ: "Europe/Brussels"
  PGID: "100"
  PUID: "1027"

services:
  jackett:
    image: linuxserver/jackett:latest
    restart: unless-stopped
    ports:
      - 9117:9117/tcp
    environment:
      <<: *common-variables
    hostname: liofal.synology.me
    volumes:
      - /volume1/docker/jackett/config:/config
      - /volume1/incoming:/downloads
    logging:
      driver: syslog
    deploy:
      resources:
        limits:
          memory: 128M
    networks:
      radarr:
  
  transmission:
    image: linuxserver/transmission:latest
    restart: unless-stopped
    ports:
      - 9091:9091/tcp
      - 51413:51413/tcp
    environment:
      <<: *common-variables
    hostname: liofal.synology.me
    volumes:
      - /volume1/docker/transmission/config2:/config
      - /volume1/radarr:/downloads
      - /volume1/incoming:/watch
    logging:
      driver: syslog
    deploy:
      resources:
        limits:
          memory: 128M
    depends_on: 
      - jackett
    links: 
      - jackett
    networks:
      radarr:
  
  radarr:
    image: linuxserver/radarr:latest
    restart: unless-stopped
    ports:
      - 7878:7878/tcp
    environment:
      <<: *common-variables
    hostname: liofal.synology.me
    volumes:
      - /volume1/docker/radarr/config:/config
      - /volume1/radarr:/downloads
      - /volume1/movies:/movies
    logging:
      driver: syslog
    deploy:
      resources:
        limits:
          memory: 128M
    depends_on: 
      - transmission
    links: 
      - transmission
    networks:
      radarr:
  
networks:
  radarr: