version: '3.7'

services:
  radarr:
    image: linuxserver/radarr:latest
    restart: unless-stopped
    ports:
      - 7878:7878/tcp
    env_file: 
        - .env
        - ../global.env    
    hostname: liofal.synology.me
    volumes:
      - /volume1/docker/radarr/config:/config
      - /volume1/radarr:/downloads/complete/radarr
      - /volume1/movies:/movies
    logging:
      driver: json-file
    deploy:
      resources:
        limits:
          memory: 128M
    networks:
      radarr:
      jackett:
      transmission:
  
networks:
  radarr:
    name: radarr
  jackett:
    external: 
      name: jackett
  transmission:
    external: 
      name: transmission
  