version: "3.7"
services:
  watchtower:
    image: v2tec/watchtower
    restart: unless-stopped
    logging:
      driver: syslog
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 30
    logging:
      driver: syslog
