version: '3.7'

services:
  jackett:
    image: linuxserver/jackett:latest
    restart: unless-stopped
    ports:
      - 9117:9117/tcp
    env_file: 
        - .env
        - ../global.env    
    hostname: liofal.synology.me
    volumes:
      - /volume1/docker/jackett/config:/config
      - /volume1/incoming:/downloads
    logging:
      driver: json-file
    deploy:
      resources:
        limits:
          memory: 128M
    networks:
      jackett:
  
networks:
  jackett:
    name: jackett
