version: '3.7'

services:
  jenkins:
    image: jenkins/jenkins:alpine
    restart: unless-stopped
    ports:
      - 8080:8080/tcp
      - 50000:50000/tcp
    env_file: 
        - .env
        - ../global.env    
    hostname: liofal.synology.me
    volumes:
      - /volume1/docker/jenkins/config:/var/jenkins_home
      - /volume1/incoming:/downloads
    logging:
      driver: json-file
    deploy:
      resources:
        limits:
          memory: 128M
    networks:
      jenkins:
  
networks:
  jenkins:
    name: jenkins
