version: '3.7'

services:
  bazarr:
    image: linuxserver/bazarr:latest
    restart: unless-stopped
    ports:
      - 6767:6767/tcp
    env_file: 
        - .env
        - ../global.env    
    hostname: liofal.synology.me
    volumes:
      - /volume1/docker/bazarr/config:/config/config
      - /volume1/docker/bazarr/db:/config/db
      - /volume1/docker/bazarr/log:/config/log
      - /volume1/movies:/movies
      - /volume1/tvshows:/tv:ro
    logging:
      driver: json-file
    deploy:
      resources:
        limits:
          memory: 128M
    networks:
      radarr:
      sonarr:
  
networks:
  sonarr:
    external: 
      name: sonarr
  radarr:
    external: 
      name: radarr