version: '3.7'

services:
  transmission:
    image: linuxserver/transmission:latest
    restart: unless-stopped
    ports:
      - 9091:9091/tcp
      - 51413:51413/tcp
    env_file: 
        - .env
        - ../global.env    
    hostname: liofal.synology.me
    volumes:
      - /volume1/docker/transmission/config2:/config
      - /volume1/radarr:/downloads/complete/radarr
      - /volume1/sonarr:/downloads/complete/sonarr
      - /volume1/incoming:/watch
    logging:
      driver: json-file
    deploy:
      resources:
        limits:
          memory: 128M
    networks:
      transmission:
  
networks:
  transmission:
    name: transmission  